### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by HumanityI** [simon-weber/gchatautorespond#12]
needs a update for requirement files to covering this error

`~/gchatautorespond$  python standalone_bot.py auth
Traceback (most recent call last):
  File "standalone_bot.py", line 23, in <module>
    from docopt import docopt
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/docopt.py", line 10, in <module>
    import re
  File "/usr/lib/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'`

**Comment by simon-weber** [comment]
Gotcha; thanks for reporting this. I'll look into this in more detail when I have a chance, but I suspect you can just `pip uninstall enum34` to get it working again.
